### ISSUE TITLE
remap Edit to F2

### ISSUE THREAD

**Issue by omega3** [Arthaey/anki-custom-keyboard-shortcuts#2]
Can you please add option to your add-on to remap Edit to F2 (instead of "e"). I am used to use F2 in file manager for editing file names. 
But the more important reason is that when I have in my card spell-check and press letter "e" Anki treats it as a first letter, a beginning of a new word and it doesn't switch to edit mode. If this is the case Anki enters edit mode only after answer is shown. 
Of course I can live with that but I have to remember about it. With suitable add-on using Anki would be much easier, especially when someone edits a lot, as I do. I constantly improve my decks. 
Thank you in advance.

**Comment by ankitest** [comment]
@omega3 You can try to use [• F4 Edit](https://ankiweb.net/shared/info/2085904433)  
_Usually GUI standards stand for: F2 rename F3 view F4 edit_

**Comment by omega3** [comment]
That solves the problem. Thank you very much.
