### ISSUE TITLE
Any progress with the other commands?

### ISSUE THREAD

**Issue by gemena** [Arthaey/anki-custom-keyboard-shortcuts#4]
Once upon a time you've written on your To-Do list that "allow customizing of other shortcuts". Is there any progress on that front? I'd especially like to change the "f" and "e" commands.

Related question: Is there a way to set the add-on so that the default shortcuts are simply disabled? I mean without replacing them with any other key?

**Comment by Arthaey** [comment]
I know that the "f" command creates a filtered deck by default, but what does "e" do?

As for disabling them, I've just added that ability for you! :) If you get the latest version of the addon, you should see a section at the top that looks like this:

```
# TO DISABLE A SHORTCUT ENTIRELY, DELETE THE '#' IN FRONT OF IT.
DISABLED_SHORTCUTS = [
    #GLOBAL_DECKS_SHORTCUT,
    #GLOBAL_OVERVIEW_SHORTCUT,
    #GLOBAL_ADD_SHORTCUT,
    #GLOBAL_BROWSE_SHORTCUT,
    #GLOBAL_STATS_SHORTCUT,
    #GLOBAL_SYNC_SHORTCUT,
]
```

Say you want to make the Browse shortcut ("b" by default) do nothing. You would delete the "#" in front of that line. So change that section of the code to look like this:

```
# TO DISABLE A SHORTCUT ENTIRELY, DELETE THE '#' IN FRONT OF IT.
DISABLED_SHORTCUTS = [
    #GLOBAL_DECKS_SHORTCUT,
    #GLOBAL_OVERVIEW_SHORTCUT,
    #GLOBAL_ADD_SHORTCUT,
    GLOBAL_BROWSE_SHORTCUT,
    #GLOBAL_STATS_SHORTCUT,
    #GLOBAL_SYNC_SHORTCUT,
]
```

Does that do what you were hoping for?

**Comment by Arthaey** [comment]
Oh, I see, you mean "e" when reviewing cards, not on the deck list screen.

It turns out that Anki creates the "f" shortcut differently from the others, so I'll have to get back to you on support that one.

**Comment by gemena** [comment]
Thank you! That disabling option is perfect!

I've left feedback about the shortcuts [on Anki discussion board here](https://anki.tenderapp.com/discussions/ankidesktop/24092-suggestion-add-option-to-disable-or-customise-shortcuts-or-alternatively-make-shortcuts-less-accident-prone). But until anything happens with the official release your add-on is the best solution to this problem.

Yes, I'm trying to disable the shortcuts during reviewing cards. I am using cards which require written input. If the focus shifts away from the input window then Anki will respond to the shortcuts.

The focus shifts away from the input window easily, for example if my wrist brushes against the trackpad on my laptop. And even more commonly some add-ons cause this, like using the "Later, not not button".

It causes mayhem if the focus shifts without my noticing and I try to answer a card by writing a sentence. So many basic keys trigger something unwanted. :(

The "e" for Edit is probably the worst. The first "e" I type opens the edit window and the rest of sentence I'm typing gets entered onto the card itself.

**Comment by Arthaey** [comment]
Ugh, I can see why you want to disable shortcuts when reviewing!

I'm glad I could help a little, and I hope Damien is able to make an official change to help you out. :)
