### ISSUE TITLE
app shortcuts intervene with diacritic signs 

### ISSUE THREAD

**Issue by Silezmogul** [Arthaey/anki-custom-keyboard-shortcuts#6]
Hi there, 

ALT+A and ALT+S are shortcuts in polish language for ą and ś signs. App shortcuts it intervene with their use. I have found an addon to edit shortcuts but this shortcut was not ammong them.

d I haven't found a way to edit this shortcut and even if I did I would have to do it on every reinstall.

How can you help me with this?

Best,
Sebastian

**Comment by Arthaey** [comment]
That sounds frustrating to have the shortcuts conflict with letters you need to type all the time! Luckily, it's fairly easy to edit the shortcuts:

1. Go to the main deck list window.
2. Open the menu item **Tools > Add-ons > CustomKeyboardShortcuts > Edit...**
3. [Go to line 16](https://github.com/Arthaey/anki-custom-keyboard-shortcuts/blob/master/CustomKeyboardShortcuts.py#L16) or so, where it says "CUSTOMIZE THESE SHORTCUT KEYS."
4. **Change the letters** to whatever you'd like them to be.
5. Click the **Save button**.
6. **Restart** Anki.

Hope that helps!
